database:
  type: postgres
  config_file: "db_config.py"

ingestions:
  - type: csv
    path: "data/test.csv"
    schema_name: "raw"
    table_name: "clientes_ext"

  - type: csv_external
    path: "data/test.csv"
    schema_name: external_2
    table_name: clientes_ext_4

  - type: postgres
    source_schema: "test"
    source_table: "test"
    schema_name: "raw"
    table_name: "orders_ext"
    source_db_config: "db_config.py"

transformations: []
analytics: null
